apiVersion: devops.stillforward.de/v1alpha1
kind: DevEnvironmentClaim
metadata:
  name: dev-env-tom-s-claming-tom
  namespace: tom
spec:
    databaseLocation: "EU"
    databaseStorageSize: 13
    # - type: "databas"
    #   spec:
    #     location: "eu-central-1"
    #     storageSize: "10GB"
    # - type: "deployment"
    #   spec:
    #     replicas: "1"        
    #     cpu: "4"
    #     memory: "8GB"
    team:
      name: "Entwicklerteam A"
  # accessControl:
  #   - user: "developer1"
  #     permissions: "read-write"
  #   - user: "developer2"
  #     permissions: "read-only"