# Komposition für die AWS RDS Postgres-Datenbank und Kubernetes Deployment
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: composites.devops.stillforward.de.aws
  labels:
    provider: aws
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: devops.stillforward.de/v1alpha1
    kind: DevEnvironment
  resources:
    - name: postgresdb
      base:
        apiVersion: rds.aws.upbound.io/v1beta1
        kind: Instance
        spec:
          forProvider:
            allocatedStorage: 10
            autoGeneratePassword: true
            autoMinorVersionUpgrade: true
            backupRetentionPeriod: 14
            backupWindow: 09:46-10:16
            dbInstanceClass: db.t3.medium
            engine: postgres
            engineVersion: "13.7"
            instanceClass: db.t3.micro
            # kmsKeyIdSelector:
            #   matchLabels:
            #     testing.upbound.io/example-name: sample-key
            maintenanceWindow: Mon:00:00-Mon:03:00
            name: example
            passwordSecretRef:
              key: password
              name: example-dbinstance
              namespace: crossplane-system
            publiclyAccessible: false
            region: eu-central-1
            skipFinalSnapshot: true
            storageEncrypted: true
            storageType: gp2
            masterUsername: masteruser
          writeConnectionSecretToRef:
            name: example-dbinstance-out
            namespace: default

      patches:
        - fromFieldPath: "spec.databaseLocation"
          toFieldPath: "spec.forProvider.region"
          transforms:
            - type: map
              map:
                EU: eu-central-1
                US: us-east-1
        - fromFieldPath: "spec.databaseStorageSize"
          toFieldPath: "spec.forProvider.allocatedStorage"
      connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        - fromConnectionSecretKey: endpoint
        - fromConnectionSecretKey: port
