apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: devenvironments.devops.stillforward.de
spec:
  group: devops.stillforward.de
  names:
    kind: DevEnvironment
    plural: devenvironments
  claimNames:
    kind: DevEnvironmentClaim
    plural: devenvironmentclaim
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              resources:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    spec:
                      type: object
                      properties:
                        # Spezifikationen für die Datenbank
                        location:
                          type: string
                        storageSize:
                          type: string
                        # Spezifikationen für das Kubernetes Deployment
                        replicas:
                          type: string
                        cpu:
                          type: string
                        memory:
                          type: string
              team:
                type: object
                properties:
                  name:
                    type: string
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port