apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: devenvironments.devops.stillforward.de
spec:
  group: devops.stillforward.de
  names:
    kind: DevEnvironment
    plural: devenvironments
  claimNames:
    kind: DevEnvironmentClaim
    plural: devenvironmentclaim
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                databaseLocation:
                  type: string
                databaseStorageSize:
                  type: number
                team:
                  type: object
                  properties:
                    name:
                      type: string